---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "crawler.fullname" . }}
  labels:
    app: searchEngine
    component: crawler
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: searchEngine
      component: crawler
      release: {{ .Release.Name }}
  template:
    metadata:
      name: crawler
      labels:
        app: searchEngine
        component: crawler
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: crawler
        ports:
          - containerPort: {{ .Values.service.internalPort }}
            name: crawler
            protocol: TCP
        env:
          - name: MONGO
            value: {{ .Values.databaseHost | default (printf "%s-mongodb" .Release.Name) }}
          - name: MONGO_PORT
            value: {{ .Values.databasePort | default "27017" | quote }}
          - name: RMQ_HOST
            value: {{ .Values.databaseHost | default (printf "%s-rabbitmq" .Release.Name) }}
